---
- name: Install nginx htop and git 
  hosts: webhosts
  become: yes
  tasks:
    - name: Install nginx, htop, git
      apt:
        name:
          - nginx
          - htop
          - git
        state: present

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes
